package org.grnet.cat.dtos.subject;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Schema;

@Schema(name = "Subject", description = "This object represents a Subject.")
public class SubjectResponse {

    @Schema(
            type = SchemaType.NUMBER,
            implementation = Long.class,
            description = "Represents a unique identifier generated by CAT API.",
            example = "1"
    )
    @JsonProperty("id")
    public Long id;

    @Schema(
            type = SchemaType.STRING,
            implementation = String.class,
            description = "The subject id.",
            example = "id"
    )
    @JsonProperty("subject_id")
    public String subjectId;

    @Schema(
            type = SchemaType.STRING,
            implementation = String.class,
            description = "The subject name.",
            example = "name"
    )
    public String name;

    @Schema(
            type = SchemaType.STRING,
            implementation = String.class,
            description = "The subject type.",
            example = "type"
    )
    public String type;
}
