INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:156489G8', 'Userinfo-Family-Name-Claim-Available', 'pid_graph:G0A5FWLC', 'family_name_user_info', 'Family Name claim available in Userinfo endpoint.', 'This test verifies that the family name claim is available at the Userinfo endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:156489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the OpenID Connect UserInfo endpoint of the AAI service return Family Name information within the name claim as required by AARC-G056?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:256489G8', 'Userinfo-Email-Claim-Available', 'pid_graph:G0A5FWLC', 'email_user_info', 'Email claim available in Userinfo endpoint.', 'This test verifies that the email claim is available at the Userinfo endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:256489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the OpenID Connect UserInfo endpoint of the AAI service return Email information within the email claim as required by AARC-G056?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:356489G8', 'Userinfo-Organisation-Display-Name-Claim-Available', 'pid_graph:G0A5FWLC', 'organization_name_user_info', 'Organisation Display Name claim available in Userinfo endpoint.', 'This test verifies that the organization_name claim is available at the Userinfo endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:356489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the OpenID Connect UserInfo endpoint of the AAI service return Organisation Display Name information within the organization_name claim as required by AARC-G056?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:456489G8', 'Userinfo-Organisation-Domain-Claim-Available', 'pid_graph:G0A5FWLC', 'schac_home_organization_user_info', 'Organisation Domain claim available in Userinfo endpoint.', 'This test verifies that the schac_home_organization claim is available at the Userinfo endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:456489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the OpenID Connect UserInfo endpoint of the AAI service return Organisation Domain information within the schac_home_organization claim as required by AARC-G056?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:556489G8', 'TokenIntrospection-Organisation-Domain-Claim-Available', 'pid_graph:G0A5FWLC', 'schac_home_organization_token_introspection', 'Organisation Domain claim available in Token Introspection endpoint.', 'This test verifies that the schac_home_organization claim is available at the Token Introspection endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:556489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the Token Introspection endpoint of the AAI service return Organisation Domain information within the entitlements claim?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:656489G8', 'Userinfo-Affiliation-Home-Organisation-Claim-Available', 'pid_graph:G0A5FWLC', 'voperson_external_affiliation_user_info', 'Affiliation within Home Organisation claim available in Userinfo endpoint.', 'This test verifies that the voperson_external_affiliation claim is available at the Userinfo endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:656489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the OpenID Connect UserInfo endpoint of the AAI service return Affiliation within Home Organisation information within the voperson_external_affiliation claim as required by AARC-G056?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:756489G8', 'TokenIntrospection-Affiliation-Home-Organisation-Claim-Available', 'pid_graph:G0A5FWLC', 'voperson_external_affiliation_token_introspection', 'Affiliation within Home Organisation claim available in Token Introspection endpoint.', 'This test verifies that the voperson_external_affiliation claim is available at the Token Introspection endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:756489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the Token Introspection endpoint of the AAI service return Affiliation within Home Organisation information within the entitlements claim?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:856489G8', 'Userinfo-Group-Role-Claim-Available', 'pid_graph:G0A5FWLC', 'group_role_user_info', 'Group and Role claim available in Userinfo endpoint.', 'This test verifies that the entitlements claim is available at the Userinfo endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:856489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the OpenID Connect UserInfo endpoint of the AAI service return Group and Role information within the entitlements claim as required by AARC-G056?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:956489G8', 'TokenIntrospection-Group-Role-Claim-Available', 'pid_graph:G0A5FWLC', 'group_role_token_introspection', 'Group and Role claim available in Token Introspection endpoint.', 'This test verifies that the entitlements claim is available at the Token Introspection endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:956489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the Token Introspection endpoint of the AAI service return Group and Role information within the entitlements claim?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:016489G8', 'Userinfo-Resource-Capabilities-Claim-Available', 'pid_graph:G0A5FWLC', 'resource_capabilities_user_info', 'Resource Capabilities claim available in Userinfo endpoint.', 'This test verifies that the entitlements claim is available at the Userinfo endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:016489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the OpenID Connect UserInfo endpoint of the AAI service return Resource Capabilities information within the entitlements claim as required by AARC-G056?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:116489G8', 'TokenIntrospection-Resource-Capabilities-Claim-Available', 'pid_graph:G0A5FWLC', 'resource_capabilities_token_introspection', 'Resource Capabilities claim available in Token Introspection endpoint.', 'This test verifies that the entitlements claim is available at the Token Introspection endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:116489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the Token Introspection endpoint of the AAI service return Resource Capabilities information within the entitlements claim?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:216489G8', 'Access-Token-Assurance-Claim-Available', 'pid_graph:G0A5FWLC', 'assurance_access_token', 'Assurance claim available in Access Token.', 'This test verifies that the eduperson_assurance claim is available at the Access Token of an AARC-compliant Identity Provider.',
null, 'pid_graph:216489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the Access Token issued by the AAI service include Assurance information within the eduperson_assurance claim as required by AARC-G056?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:316489G8', 'TokenIntrospection-Assurance-Claim-Available', 'pid_graph:G0A5FWLC', 'assurance_token_introspection', 'Assurance claim available in Token Introspection endpoint.', 'This test verifies that the eduperson_assurance claim is available at the Token Introspection endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:316489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the Token Introspection endpoint of the AAI service return Assurance information within the entitlements claim?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:416489G8', 'Userinfo-Sub-Claim-Available', 'pid_graph:G0A5FWLC', 'sub_user_info', 'Public Subject Identifier claim available in Userinfo endpoint.', 'This test verifies that the sub claim is available at the Userinfo endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:416489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the OpenID Connect UserInfo endpoint of the AAI service return Public Subject Identifier information within the sub claim as required by AARC-G056?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:516489G8', 'Access-Token-Sub-Claim-Available', 'pid_graph:G0A5FWLC', 'sub_access_token', 'Public Subject Identifier claim available in Access Token.', 'This test verifies that the sub claim is available at the Access Token of an AARC-compliant Identity Provider.',
null, 'pid_graph:516489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the Access Token issued by the AAI service include Public Subject Identifier information within the sub claim as required by AARC-G056?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:616489G8', 'TokenIntrospection-Sub-Claim-Available', 'pid_graph:G0A5FWLC', 'sub_token_introspection', 'Public Subject Identifier claim available in Token Introspection endpoint.', 'This test verifies that the sub claim is available at the Token Introspection endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:616489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the Token Introspection endpoint of the AAI service return Public Subject Identifier information (sub claim) within the entitlements claim?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:716489G8', 'Userinfo-VoPerson-Id-Claim-Available', 'pid_graph:G0A5FWLC', 'voperson_id_user_info', 'Public Subject Identifier claim available in Userinfo endpoint.', 'This test verifies that the voperson_id claim is available at the Userinfo endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:716489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the OpenID Connect UserInfo endpoint of the AAI service return Public Subject Identifier information within voperson_id sub claim as required by AARC-G056?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:816489G8', 'Access-Token-VoPerson-Id-Claim-Available', 'pid_graph:G0A5FWLC', 'voperson_id_access_token', 'Public Subject Identifier claim available in Access Token.', 'This test verifies that the voperson_id claim is available at the Access Token of an AARC-compliant Identity Provider.',
null, 'pid_graph:816489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the Access Token issued by the AAI service include Public Subject Identifier information within the voperson_id claim as required by AARC-G056?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');

INSERT INTO p_Test (lodTES , TES , lodTME, testparams, labelTest, descTest, lodMTV , lodTES_V, version, labeltestdefinition, paramtype, testquestion, tooltip) VALUES ('pid_graph:916489G8', 'TokenIntrospection-VoPerson-Id-Claim-Available', 'pid_graph:G0A5FWLC', 'voperson_id_token_introspection', 'Public Subject Identifier claim available in Token Introspection endpoint.', 'This test verifies that the voperson_id claim is available at the Token Introspection endpoint of an AARC-compliant Identity Provider.',
null, 'pid_graph:916489G8', 1, 'Automated confirmation of AARC-G056 compliance', 'String', 'Does the Token Introspection endpoint of the AAI service return Public Subject Identifier information (voperson_id claim) within the entitlements claim?', 'Automatically checks if the required claim is released in compliance with the AARC-G056 specification, with no manual steps involved.');