-- ------------------------------------------------
-- Version: v1.85
--
-- Description: Migration that introduces the t_Type_Motivation and t_Motivation tables
-- -------------------------------------------------

CREATE TABLE t_Type_Motivation (
    lodTMT VARCHAR(255) NOT NULL PRIMARY KEY,
    TMT VARCHAR(255),
    labelMotivationType VARCHAR(255),
    descMotivationType TEXT,
    urlMotivationType VARCHAR(255),
    populatedBy VARCHAR(255),
    lastTouch TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lodTMT_V VARCHAR(255)
);

INSERT INTO t_Type_Motivation (lodTMT, TMT, labelMotivationType, descMotivationType, urlMotivationType, lodTMT_V) VALUES ('pid_graph:5AF642D8', 'GDS', 'Good Digital Systems', 'These motivations include risk aversion (for example by requiring two-factor authentication, open source code, and the like). For systems engineering, these will be important considerations - elements such as interoperability, modularity, topology, and scalability are included in this set of motivations.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/a9ceb5a3-15ca-4e95-908f-36cab72014a2/concept/55bdb433-3fa9-44b1-871e-a99f24bbd647', NULL);
INSERT INTO t_Type_Motivation (lodTMT, TMT, labelMotivationType, descMotivationType, urlMotivationType, lodTMT_V) VALUES ('pid_graph:5EB0883B', 'M&R', 'Mandatory, Policy, and Regulatory', 'Compliance is often mandatory, and is intended to ensure legality or a minimum level of performance. Examples include the EOSC PID Policy, or GDPR.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/a9ceb5a3-15ca-4e95-908f-36cab72014a2/concept/8dd8890d-3e29-45c6-ac13-52a858b32c90', NULL);
INSERT INTO t_Type_Motivation (lodTMT, TMT, labelMotivationType, descMotivationType, urlMotivationType, lodTMT_V) VALUES ('pid_graph:8733CC95', 'CEX', 'Community Expectation', 'These are broad community expectations of the performance of the ecosystem, and some of these are formalised in sets of principles (FAIR, TRUST, CARE) and in some cases, realised as sets of criteria and/ or elaborated as expected behaviour or levels of performance (guidance, best practices).', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/a9ceb5a3-15ca-4e95-908f-36cab72014a2/concept/a81169e9-7e52-4fb4-ad0f-7096d70a169c', NULL);
INSERT INTO t_Type_Motivation (lodTMT, TMT, labelMotivationType, descMotivationType, urlMotivationType, lodTMT_V) VALUES ('pid_graph:8882700E', 'COM', 'Composite', 'A motivation that includes aspects of more than one type, or is composed of motivations that span multiple concerns.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/a9ceb5a3-15ca-4e95-908f-36cab72014a2/concept/8dfdf546-8327-4fae-98eb-89480451e732', NULL);
INSERT INTO t_Type_Motivation (lodTMT, TMT, labelMotivationType, descMotivationType, urlMotivationType, lodTMT_V) VALUES ('pid_graph:AD9D854B', 'ROP', 'Rules of Participation', 'These ensure a minimum level of performance, readiness, or maturity as a prerequisite for participation in a network, an infrastructure, or a consortium.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/a9ceb5a3-15ca-4e95-908f-36cab72014a2/concept/e69a9f20-3726-422d-9c8a-0078c56d64d0', NULL);
INSERT INTO t_Type_Motivation (lodTMT, TMT, labelMotivationType, descMotivationType, urlMotivationType, lodTMT_V) VALUES ('pid_graph:DFE640B9', 'A&S', 'Architecture and Specifications', 'Compliance may be required for a wide variety of published and well-known standards and conventions - e.g. ISO 27001, OpenAPI, HATEOAS , and similar.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/a9ceb5a3-15ca-4e95-908f-36cab72014a2/concept/e6559d74-5434-4888-b629-f2a0ffff4601', NULL);

CREATE TABLE t_Motivation (
    lodMTV VARCHAR(255) NOT NULL PRIMARY KEY,
    MTV VARCHAR(255) NOT NULL,
    lodTMT VARCHAR(255) NOT NULL,
    labelMotivation VARCHAR(255) NOT NULL,
    decMotivation TEXT NOT NULL,
    lodMTV_P VARCHAR(255) DEFAULT NULL,
    populatedBy VARCHAR(255) DEFAULT NULL,
    lastTouch TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lodMTV_V VARCHAR(255) DEFAULT NULL,
    FOREIGN KEY (lodTMT) REFERENCES t_Type_Motivation(lodTMT)
);

INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:0743BE89', 'DataCommons', 'pid_graph:AD9D854B', 'Data Commons', 'The Data Commons Graph aggregates data from many different data sources into a single database. Data Commons is based on the data model used by schema.org; for more information, see the guide to the data model.', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:09F8F535', 'LIC', 'pid_graph:5EB0883B', 'Licence Compliance', 'Various approaches are being developed, using ORDL-compliant encodings of conditions, to be evaluated as automatically as possible against the performance of the requestor.', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:0ACD7064', 'FDM', 'pid_graph:8733CC95', 'FAIR Data Maturity', '“To remedy the proliferation of FAIRness measurements based on different interpretations of the principles, an RDA Working Group … established a set of indicators and maturity levels for those indicators.”', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:262F3417', 'FAIR-AWARE', 'pid_graph:8733CC95', 'FAIR-Aware', '“The tool is discipline-agnostic, making it relevant to any scientific field. … The self-assessment consists of 10 questions with additional guidance texts to help you become more aware of what you can do to make your data(set) as FAIR as possible. The assessment will take between 10-30 minutes, after which you will receive an overview of your awareness level and additional tips on how you can further improve your FAIR skills.”', 'pid_graph:8DFF7D4B', NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:2B811A6F', 'TRUST-NES', 'pid_graph:8733CC95', 'nestor', 'German National Standard DIN 31644, used for trustworthy long-term repositories', 'pid_graph:FF0C6304', NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:3E109BBA', 'EOSC-PID', 'pid_graph:5EB0883B', 'EOSC PID Policy', 'A policy developed for PID ecosystem in EOSC, supplemented by refinements and extensions from the EOSC Task Force on PID Policy', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:42455014', 'F-UJI', 'pid_graph:8733CC95', 'F-UJI', '“F-UJI is a web service to programmatically assess FAIRness of research data objects at the dataset level based on the FAIRsFAIR Data Object Assessment Metrics”.', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:42ED7AC2', 'POSI', 'pid_graph:AD9D854B', 'Principles of Open Scholarly Infrastructure', 'POSI offers a set of guidelines by which open scholarly infrastructure organisations and initiatives that support the research community can be run and sustained. Others have since built on the foundation of POSI to discuss and propose how all those that support scholarly communications can use these principles to hold each other accountable.', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:448F84CA', 'TRUST-ISO', 'pid_graph:8733CC95', 'ISO 16363', 'ISO 16363:2012 defines a recommended practice for assessing the trustworthiness of digital repositories. It is applicable to the entire range of digital repositories. ISO 16363:2012 can be used as a basis for certification.', 'pid_graph:FF0C6304', NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:54B11253', 'EVA', 'pid_graph:8733CC95', 'FAIR-Eva Assessment', '“Fair EVA is an open source project that is gathering resources and building tools to help researchers and developers, technology activists and voice technology users evaluate and audit bias and discrimination in voice technologies.”', 'pid_graph:8DFF7D4B', NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:580DFF47', 'PubReq', 'pid_graph:AD9D854B', 'Publisher’s requirements for repository selection', 'Representatives from journals, journal publishers and scholarly communication organisations have come together in the FAIRsharing Community to propose a set of criteria for the identification and selection of those data repositories that accept research data submissions.', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:5A120D3A', 'FAIR-PRI', 'pid_graph:8733CC95', 'FAIR Principles', '“FAIR data are data which meet principles of findability, accessibility, interoperability, and reusability. The acronym and principles were defined in a March 2016 paper in the journal Scientific Data by a consortium of scientists and organisations. The FAIR principles emphasise machine-actionability.”', 'pid_graph:8DFF7D4B', NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:6915DF88', 'SP', 'pid_graph:8733CC95', 'SignPosting', '“Signposting is an approach to make the scholarly web more friendly to machines. It uses Typed Links as a means to clarify patterns that occur repeatedly in scholarly portals. For resources of any media type, these typed links are provided in HTTP Link headers. For HTML resources, they may additionally be provided in HTML link elements.”', 'pid_graph:8DFF7D4B', NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:75ACDD17', 'CURE-FAIR', 'pid_graph:8733CC95', 'CURE-FAIR RDA Working Group', 'The working group has published a number of resources to assist with reproducibility.', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:76655FA7', 'TRUST-CTS', 'pid_graph:8733CC95', 'CoreTrustSeal', '“The CoreTrustSeal Trustworthy Data Repositories Requirements reflect the characteristics of trustworthy repositories. As such, all Requirements are mandatory and are equally weighted, standalone items. Although some overlap is unavoidable, duplication of evidence sought among Requirements has been kept to a minimum where possible.”', 'pid_graph:FF0C6304', NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:791E870C', 'TRUST-PRI', 'pid_graph:8733CC95', 'TRUST Principles', '“The TRUST Principles provide a common framework to facilitate discussion and implementation of best practice in digital preservation by all stakeholders.”', 'pid_graph:FF0C6304', NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:89082276', 'FSA', 'pid_graph:8733CC95', 'FAIR Semantic Artefacts', '“17 preliminary recommendations related to one or more of the FAIR principles, and 10 best practice recommendations on semantic artefacts were documented.”', 'pid_graph:8DFF7D4B', NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:8B9A9015', 'CARE', 'pid_graph:8733CC95', 'CARE', 'Ethical research-related motivations', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:8DFF7D4B', 'FAIR', 'pid_graph:8733CC95', 'FAIR', 'The collection of FAIR-related motivations', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:97171FB2', 'CARE-PRI', 'pid_graph:8733CC95', 'CARE Principles', '“The current movement toward open data and open science does not fully engage with Indigenous Peoples rights and interests. Existing principles within the open data movement (e.g. FAIR: findable, accessible, interoperable, reusable) primarily focus on characteristics of data that will facilitate increased data sharing among entities while ignoring power differentials and historical contexts. The emphasis on greater data sharing alone creates a tension for Indigenous Peoples who are also asserting greater control over the application and use of Indigenous data and Indigenous Knowledge for collective benefit.”', 'pid_graph:8B9A9015', NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:986123FA', 'OCE', 'pid_graph:AD9D854B', 'Open Call Evaluation', 'An anonymised open call aimed at funding applications meeting a set of defined criteria.', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:9A5B650F', 'FDO', 'pid_graph:8733CC95', 'FAIR Data Objects', 'FAIR Digital Objects (FDO) provide a conceptual and implementation framework to develop scalable cross-disciplinary capabilities, deal with the increasing data volumes and their inherent complexity, build tools that help to increase trust in data, create mechanisms to efficiently operate in the domain of scientific assertions, and promote data interoperability.', 'pid_graph:8DFF7D4B', NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:BC8C2D2E', 'DataSpace', 'pid_graph:AD9D854B', 'FAIR Data Spaces', '“The Federated FAIR Data Space (F2DS) provides tools for both data producers and data consumers contributing to enhance the overall FAIRness of datasets natively dispersed across heterogeneous repositories by realising services for datasets homogenisation, enrichment and onboarding and services for seamless discovery and access.”', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:BE36CD9E', 'RO-CRATE', 'pid_graph:8733CC95', 'Research Objects, RO-Crate', '“An RO-Crate is a structured archive of all the items that contributed to a research outcome, including their identiﬁers, provenance, relations and annotations … RO-Crate simpliﬁes the process of making research outputs FAIR while also enhancing research reproducibility.”', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:C2FBFF44', 'ServReg', 'pid_graph:AD9D854B', 'Service Registration', 'The EOSC Rules of Participation is being refined and developed by the Task Force on Rules of Participation.', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:C6B2D50E', 'SOLID', 'pid_graph:AD9D854B', 'SOLID and Decentralised Pods', '“Solid is a specification that lets people store their data securely in decentralised data stores called Pods. Pods are like secure personal web servers for data. When data is stored in someone''s Pod, they control which people and applications can access it.” Evaluating these access requests provides a standardised basis for compliance assessment.', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:E3DF4CB4', 'FIP', 'pid_graph:AD9D854B', 'FAIR Implementation Profiles', '“The FAIR Implementation Profiles representing the implementation strategies of various communities can be used as the basis to optimise the reuse of existing FAIR-enabling resources and interoperation within and between domains. Ready-made and well-tested FAIR Implementation Profiles created by trusted communities can find widespread reuse among other communities, and vastly accelerate convergence onto well-informed FAIR implementations.” As such, the FIPs represent an encoding and implicit vocabulary for identification of FAIR criteria and measures.', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:F03AE5EB', 'FDP', 'pid_graph:AD9D854B', 'FAIR Data Points', '“A FAIR Data Point (sometimes abbreviated to FDP) is the realisation of the vision of a group of authors of the original paper on FAIR on how (meta)data could be presented on the web using existing standards, and without the need of APIs.”', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:F5CAD21E', 'WDS', 'pid_graph:AD9D854B', 'World Data System', 'The World Data System provides an interesting perspective: in addition to requiring CTS certification, repositories are required to satisfy a set of additional criteria of membership.', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:F9E7BDAE', 'GDPR', 'pid_graph:5EB0883B', 'GDPR Compliance', 'Across the EU, this is a major consideration, and while exact requirements are slightly different between countries, compliance assessment can be standardised to a large degree. Complex array of compliance elements.', NULL, NULL, NULL);
INSERT INTO t_Motivation (lodMTV, MTV, lodTMT, labelMotivation, decMotivation, lodMTV_P, populatedBy, lodMTV_V) VALUES ('pid_graph:FF0C6304', 'TRUST', 'pid_graph:8733CC95', 'TRUST', 'The collection of trust-related motivations', NULL, NULL, NULL);
