-- ------------------------------------------------
-- Version: v1.2
--
-- Description: Migration that creates the t_Actor table
-- -------------------------------------------------

CREATE TABLE t_Actor (
     ACT VARCHAR (255) NOT NULL,
     lodActor VARCHAR(255) NOT NULL PRIMARY KEY,
     labelActor VARCHAR (255) NOT NULL,
     descActor TEXT NOT NULL,
     uriActor VARCHAR (255),
     populatedBy VARCHAR(255),
     lastTouch  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     lodACT_V VARCHAR(255),
     lodMTV VARCHAR(255) DEFAULT NULL
);

INSERT INTO t_Actor ( ACT, lodActor, labelActor, descActor, uriActor,  populatedBy,  lodACT_V) VALUES ('0E00C332', 'pid_graph:0E00C332', 'PID Scheme (Component)', 'A set of rules and standards defining the nature of a PID. This would include a set of lexical formatting rules for PIDs within a namespace. It could also define for example: associated PID Type; definition of associated metadata; quality assurance conditions; usage rights, terms and conditions, and algorithmic methods for generating PID names and enforcing PID properties.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/9c735525-960e-4f13-a74d-4eb23ea9c308/concept/e5b07c01-3a86-4ceb-b59b-1df91f1be391', NULL,  NULL);
INSERT INTO t_Actor ( ACT, lodActor, labelActor, descActor, uriActor,  populatedBy,  lodACT_V) VALUES ( '1A718108', 'pid_graph:1A718108', 'PID Authority (Role)', 'A controller responsible for maintaining the rules for defining the integrity of PIDs within a PID Scheme. These rules may include setting standards for lexical formats, algorithms and protocols to ensure global uniqueness, together with setting quality of service conditions to enforce compliance to the rules. PID Authorities may be organisations (e.g. DOI.org), which enforce control over a PID infrastructure. An Authority may also be one which do not have a central control (for example Software Heritage persistent identifiers1 and W3C’s Decentralized Identifiers2), but provide a community standardisation mechanism that specifies the conformance of PIDs to a PID Scheme.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/9c735525-960e-4f13-a74d-4eb23ea9c308/concept/921a4876-d61b-4699-92d2-3c562333a934',  NULL,  NULL);
INSERT INTO t_Actor ( ACT, lodActor, labelActor, descActor, uriActor,  populatedBy,  lodACT_V) VALUES ( '20A7A125', 'pid_graph:20A7A125', 'End User (Role)', 'The end user of PID Services, for example researchers, or software, or services produced to support researchers.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/9c735525-960e-4f13-a74d-4eb23ea9c308/concept/b560cad3-4875-453a-822a-07686039a118', NULL, NULL);
INSERT INTO t_Actor ( ACT, lodActor, labelActor, descActor, uriActor,  populatedBy,  lodACT_V) VALUES ( '234B60D8', 'pid_graph:234B60D8', 'Compliance Monitoring (Role)', 'On completion, the work will support an additional role and associated component for the EOSC PID Policy, as follows: Compliance Monitoring (Role) - One or more organisations that provide services to monitor and/ or enforce compliance (with PID Policy), resulting in interoperable and aggregatable compliance metrics for the roles and components foreseen in the policy.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/9c735525-960e-4f13-a74d-4eb23ea9c308/concept/ce148a85-ee85-4c88-8e6c-34b9f281dd61', NULL,  NULL);
INSERT INTO t_Actor ( ACT, lodActor, labelActor, descActor, uriActor,  populatedBy,  lodACT_V) VALUES ( '566C01F6', 'pid_graph:566C01F6', 'PID Service (Component)', 'Basic services are those that create, manage and resolve PIDs and their associated kernel information which conforms to a PID Scheme. Advanced, value-added services may also be provided, for example attribute search or metrics.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/9c735525-960e-4f13-a74d-4eb23ea9c308/concept/88efe9f8-6f08-4b31-b6b6-2324d1d9d604', NULL,  NULL);
INSERT INTO t_Actor ( ACT, lodActor, labelActor, descActor, uriActor,  populatedBy,  lodACT_V) VALUES ( '7835EF43', 'pid_graph:7835EF43', 'Multi-Primary Administrator (MPA)(Role)', '“Each credentialed MPA operates its own GHR Services in accordance with the DONA Foundation Policies & Procedures for the GHR, and coordinates its GHR Services with other MPAs and DONA in the distributed operation of the GHR on a multi-primary basis.”', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/9c735525-960e-4f13-a74d-4eb23ea9c308/concept/0158d2b1-0ad8-45af-a94b-592c0d16bf64', NULL,  NULL);
INSERT INTO t_Actor ( ACT, lodActor, labelActor, descActor, uriActor,  populatedBy,  lodACT_V) VALUES ( 'B5CC396B', 'pid_graph:B5CC396B', 'PID Owner (Role)', 'An actor (an organisation or individual) who has the authority to create a PID, assign PID to an entity, provide and maintain accurate Kernel Information for the PID. A new PID Owner must be identified and these responsibilities transferred, if the current PID Owner is no longer able to carry them out.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/9c735525-960e-4f13-a74d-4eb23ea9c308/concept/54569135-6729-4e18-8eb3-a2217be7e62f', NULL,  NULL);
INSERT INTO t_Actor ( ACT, lodActor, labelActor, descActor, uriActor,  populatedBy,  lodACT_V) VALUES ( 'D42428D7', 'pid_graph:D42428D7', 'PID Manager (Role)', 'PID Managers have responsibilities to maintain the integrity of the relationship between entities and their PIDs, in conformance to a PID Scheme defined by a PID Authority. A PID Manager will typically subscribe to PID services to offer functionality to PID Owners within the PID Manager’s services. One example is a Service Provider which uses PID Services as part of its own service delivery. For example, PID Managers may include a provider of a data repository, a data catalogue, or a research workflow system.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/9c735525-960e-4f13-a74d-4eb23ea9c308/concept/f7f844ad-ecd5-4a51-926e-4760ad6e9580', NULL,  NULL);
INSERT INTO t_Actor ( ACT, lodActor, labelActor, descActor, uriActor,  populatedBy,  lodACT_V) VALUES ( 'E92B9B49', 'pid_graph:E92B9B49', 'PID Service Provider (Role)', 'Basic services are those that create, manage and resolve PIDs and their associated kernel information which conforms to a PID Scheme. Advanced, value-added services may also be provided, for example attribute search or metrics. An organisation which provides PID services in conformance to a PID Scheme, subject to its PID Authority. PID Service Providers have responsibility for the provision, integrity, reliability and scalability of PID Services, in particular the issuing and resolution of PIDs, but also lookup and search services, and interoperability with a generic resolution system.', 'https://mscr-test.rahtiapp.fi/vocabularies/terminology/9c735525-960e-4f13-a74d-4eb23ea9c308/concept/88efe9f8-6f08-4b31-b6b6-2324d1d9d604', NULL,  NULL);

UPDATE t_Actor SET descActor = 'Each credentialed MPA operates its own GHR Services in accordance with the DONA Foundation Policies & Procedures for the GHR, and coordinates its GHR Services with other MPAs and DONA in the distributed operation of the GHR on a multi-primary basis.' WHERE lodActor = 'pid_graph:7835EF43';

